# Generated by Django 5.1.1 on 2025-04-27 17:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Cliente",
            fields=[
                (
                    "cliente_id",
                    models.CharField(max_length=9, primary_key=True, serialize=False),
                ),
                ("name_cli", models.CharField(max_length=20)),
                ("apellido_cli", models.CharField(max_length=20)),
                ("email_cl", models.CharField(max_length=50)),
                ("telefono_cli", models.CharField(max_length=11)),
            ],
        ),
        migrations.CreateModel(
            name="Hotel",
            fields=[
                (
                    "hotel_id",
                    models.CharField(max_length=4, primary_key=True, serialize=False),
                ),
                ("name_hotel", models.CharField(max_length=15)),
                ("ciudad", models.CharField(max_length=20)),
                ("categoria", models.CharField(max_length=10)),
                ("telefono_hotel", models.CharField(max_length=11)),
            ],
        ),
        migrations.CreateModel(
            name="Habitacion",
            fields=[
                (
                    "habitacion_id",
                    models.CharField(max_length=6, primary_key=True, serialize=False),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[("S", "Standard"), ("D", "Deluxe"), ("P", "Premium")],
                        max_length=10,
                    ),
                ),
                ("capacidad", models.CharField(max_length=2)),
                ("precio", models.DecimalField(decimal_places=0, max_digits=6)),
                (
                    "hotel",
                    models.ForeignKey(
                        db_column="hotel_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.hotel",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Reserva",
            fields=[
                (
                    "reserva_id",
                    models.CharField(max_length=6, primary_key=True, serialize=False),
                ),
                ("fecha_entrada", models.DateField()),
                ("fecha_salida", models.DateField(blank=True, null=True)),
                ("cantidad_personas", models.CharField(max_length=1)),
                (
                    "cliente",
                    models.ForeignKey(
                        db_column="cliente_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.cliente",
                    ),
                ),
                (
                    "habitacion",
                    models.ForeignKey(
                        db_column="habitacion_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.habitacion",
                    ),
                ),
                (
                    "hotel",
                    models.ForeignKey(
                        db_column="hotel_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.hotel",
                    ),
                ),
            ],
            options={
                "db_table": "reserva",
            },
        ),
    ]
